spring:
  application:
    name: customer-service

  boot.admin.client.url: http://localhost:8762

management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full

logging:
  level:
    com.hazelcast: DEBUG


info.doc: http//docs.your-service.com