spring:
  application:
    name: order-service

  cache:
    type: hazelcast

management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full


server:
  port: 9095

