spring:
  application:
    name: order-service

  cache:
    type: hazelcast

management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full

  metrics:
    # common tags that are applied to every meter needed by https://grafana.com/dashboards/4701
    tags:
      application: ${spring.application.name}

server:
  port: 9095

